# Generated by Django 3.2.3 on 2021-06-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_blogmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
