# Generated by Django 3.2.3 on 2021-06-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_blogmodel_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
